### ISSUE TITLE
Support Docker image from basic Alpine image

### ISSUE THREAD

**Issue by nbaars** [safe-waters/docker-lock#102]
**Problem**

The current Docker image is build from `scratch` this unfortunately does not work in a Gitlab-ci pipeline as it requires a shell to be present. It results in a descriptive error: "Unable to upgrade connection...."

**Proposal**

Supply Docker images for the most popular Linux distros as well (alpine/debian etc). This way the Docker image can be reused immediately in a Gitlab pipeline as follows:

```
check:
  image:
    name: safewaters/docker-lock:0.8.5
    entrypoint: [ "" ]
  stage: validate
  script:
    - docker-lock lock verify 
```

**Comment by michaelperel** [comment]
@nbaars The way the docker image is intended to be run is as follows:

```
docker run -v "${PWD}":/run safewaters/docker-lock [COMMANDS]
```

For verify, for instance:
```
docker run -v "${PWD}":/run safewaters/docker-lock lock verify
```

I have not used Gitlab, but instead of running a script and using the entrypoint, I imagine they must support commands with something like:
```
check:
  image:
    name: safewaters/docker-lock:0.8.5
    command: [ "lock", "verify" ]
  stage: validate
 ```
and I also assume they have a way of doing volume mounts (the volume mount is necessary to get the dockerfiles in the container)? If this is not possible, then I am happy to support other base images, but one of the benefits of Go is that you can use scratch and pass in a statically compiled binary so you don't need to worry about keeping the base image up-to-date/patching security issues.
