### ISSUE TITLE
Suggestion: Expand default `--dockerfile-globs`

### ISSUE THREAD

**Issue by loynoir** [safe-waters/docker-lock#121]
https://docs.docker.com/compose/compose-file/build/

```yaml
build:
  context: .
  dockerfile: webapp.Dockerfile
```

Official docs cover usage of `*.Dockerfile`.
